---
version: "2"
services:
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
      - UMASK_SET=022 #optional
    volumes:
      - ./sonnar/data:/config
      - ./sonnar/tv:/tv
      - ./downloads:/downloads
    # ports:
    #   - 8989:8989
    restart: unless-stopped
    networks:
      - webnet
    depends_on:
      - "qbittorrent"
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
      - UMASK_SET=022 #opTorrentRssIndexertional
    volumes:
      - ./radarr/data:/config
      - ./radarr/movies:/movies
      - ./downloads:/downloads
    # ports:
    #   - 8990:7878
    restart: unless-stopped
    networks:
      - webnet
    depends_on:
      - "qbittorrent"
  emby:
    image: linuxserver/emby
    container_name: emby
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - ./emby/data:/config
      - ./sonnar/tv.:/data/tvshows
      - ./radarr/movies:/data/movies
      - ./emby/transcoding:/transcode #optional
    ports:
      - 8096:8096 # need to be exposed for Emby App.
    devices:
      - /dev/dri:/dev/dri #optional
    restart: unless-stopped
    networks:
      - webnet
# Qbittorrent
  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
      - UMASK_SET=022sonarr
      - WEBUI_PORT=8080
    volumes:
      - ./qbittorrent:/config
      - ./downloads:/downloads
    # ports:
    #   - 6881:6881
    #   - 6881:6881/udp
    #   - 8080:8080
    restart: unless-stopped
    networks:
      - webnet
  nginx:
    image: linuxserver/nginx
    container_name: nginx
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - ./nginx:/config
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    depends_on:
      - "qbittorrent"
      - "emby"
      - "sonarr"
    networks:
      - webnet

networks:
  webnet:
