---
version: "2"
services:
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
      - UMASK_SET=022 #optional
    volumes:
      - ./sonnar/data:/config
      - ./sonnar/tv:/tv
      - ./downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
    networks:
      - webnet
    depends_on:
      - "qbittorrent"
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
      - UMASK_SET=022 #opTorrentRssIndexertional
    volumes:
      - ./raddar/data:/config
      - ./raddar/movies:/movies
      - ./downloads:/downloads
    ports:
      - 8990:7878
    restart: unless-stopped
    networks:
      - webnet
    depends_on:
      - "qbittorrent"
  emby:
    image: linuxserver/emby
    container_name: emby
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - ./emby/data:/config
      - ./sonnar/tv.:/data/tvshows
      - ./raddar/movies:/data/movies
      - ./emby/transcoding:/transcode #optional
    ports:
      - 8096:8096
      - 8920:8920 #optional
    devices:
      - /dev/dri:/dev/dri #optional
    restart: unless-stopped
# Qbittorrent
  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
      - UMASK_SET=022
      - WEBUI_PORT=8080
    volumes:
      - ./qbittorrent:/config
      - ./downloads:/downloads
    # ports:
    #   - 6881:6881
    #   - 6881:6881/udp
    #   - 8080:8080
    restart: unless-stopped
    networks:
      - webnet
networks:
  webnet:
